version: '3.3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbit-mq:/var/lib/rabbitmq/"
      - "rabbit-mq:/var/log/rabbitmq"
    environment:
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_DEFAULT_USER=user"
      - "RABBITMQ_DEFAULT_VHOST=/"
    expose:
      - 5672
      - 15672

volumes:
  rabbit-mq: